name: Deploy to Oracle Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  

    - name: Deploy to Oracle Cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ORACLE_HOST }}
        username: ${{ secrets.ORACLE_USER }}
        key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/AiStock/finalCapstone

           # 이전 서버 프로세스 종료
          if [ -f django_server.pid ]; then
            pid=$(cat django_server.pid)
            if ps -p $pid > /dev/null; then
              kill $pid
              echo "Previous Django server (PID: $pid) stopped."
            else
              echo "No running Django server found with PID: $pid"
            fi
            rm django_server.pid
          else
            echo "No PID file found. Server might not be running."
          fi
          
          sudo git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          nohup python3 manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &
          sleep 2
          echo "Deployment completed!"
